import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Brain, Database, Search, Quote, BookOpen, Tag, Clock, ArrowLeft, Github, Twitter, Linkedin } from 'lucide-react';

export default function FeaturesPage() {
  return (
    <div className="flex flex-col min-h-screen bg-black text-white">
      <header className="fixed w-full z-50">
        <div className="mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-center h-16">
            <nav className="flex items-center justify-center px-8 py-3 rounded-full bg-[#111111]/80 backdrop-blur-md border border-[#333333]/50 mt-4">
              <div className="flex items-center gap-2 mr-6">
                <Brain className="h-5 w-5 text-purple-400" />
                <span className="font-bold">Synapse</span>
              </div>
              <div className="hidden md:flex space-x-8">
                <Link href="/" className="text-sm font-medium text-white/70 hover:text-white">
                  Home
                </Link>
                <Link href="/#features" className="text-sm font-medium text-white/90 hover:text-white">
                  Features
                </Link>
                <Link href="https://github.com" className="text-sm font-medium text-white/70 hover:text-white">
                  Github
                </Link>
              </div>
              <div className="ml-6">
                <Link href="/dashboard">
                  <Button variant="outline" size="sm" className="text-sm bg-transparent border-[#333333] hover:bg-[#333333]/50">
                    Dashboard
                  </Button>
                </Link>
              </div>
            </nav>
          </div>
        </div>
      </header>
      
      <main className="flex-1 pt-24">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-grid-pattern relative">
          <div className="absolute inset-0 hero-gradient"></div>
          <div className="container mx-auto px-4 md:px-6 relative z-10">
            <div className="max-w-4xl mx-auto flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl glow-text">
                  Synapse Features
                </h1>
                <p className="mx-auto max-w-[700px] text-white/70 md:text-xl">
                  Discover how Synapse can transform the way you store and retrieve your knowledge.
                </p>
              </div>
            </div>
          </div>
        </section>
        
        <section className="w-full py-12 md:py-24 lg:py-32 bg-black">
          <div className="container mx-auto px-4 md:px-6">
            <div className="max-w-7xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
              <div className="feature-card rounded-xl p-8">
                <div className="feature-icon">
                  <Database className="h-6 w-6 text-purple-400" />
                </div>
                <h3 className="text-xl font-bold">Universal Storage</h3>
                <p className="text-white/70">
                  Save any type of content including quotes, text snippets, links, notes, and more in your personal knowledge base.
                </p>
              </div>
              <div className="feature-card rounded-xl p-8">
                <div className="feature-icon">
                  <Search className="h-6 w-6 text-purple-400" />
                </div>
                <h3 className="text-xl font-bold">Semantic Search</h3>
                <p className="text-white/70">
                  Find what you're looking for with AI-powered vector search that understands meaning, not just keywords.
                </p>
              </div>
              <div className="feature-card rounded-xl p-8">
                <div className="feature-icon">
                  <Brain className="h-6 w-6 text-purple-400" />
                </div>
                <h3 className="text-xl font-bold">AI-Generated Answers</h3>
                <p className="text-white/70">
                  Get concise answers based on your stored knowledge, generated by advanced AI.
                </p>
              </div>
              <div className="feature-card rounded-xl p-8">
                <div className="feature-icon">
                  <Tag className="h-6 w-6 text-purple-400" />
                </div>
                <h3 className="text-xl font-bold">Smart Tagging</h3>
                <p className="text-white/70">
                  Organize your knowledge with tags to create connections between related pieces of information.
                </p>
              </div>
            </div>
          </div>
        </section>
        
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#0A0A0A] relative">
          <div className="absolute inset-0 bg-grid-pattern opacity-10"></div>
          <div className="absolute inset-0 hero-gradient"></div>
          <div className="container mx-auto px-4 md:px-6 relative z-10">
            <div className="max-w-4xl mx-auto flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl glow-text">
                  Ready to Enhance Your Second Brain?
                </h2>
                <p className="mx-auto max-w-[700px] text-white/70 md:text-xl">
                  Start storing and retrieving your knowledge more effectively today.
                </p>
              </div>
              <div className="flex flex-col sm:flex-row gap-4 mt-8">
                <Link href="/dashboard">
                  <Button size="lg" className="gap-2 bg-white text-black hover:bg-white/90 glow-button">
                    <Brain className="h-4 w-4" />
                    Go to Dashboard
                  </Button>
                </Link>
                <Link href="/">
                  <Button size="lg" variant="outline" className="gap-2 bg-transparent border-[#333333] hover:bg-[#333333]/50">
                    <ArrowLeft className="h-4 w-4" />
                    Back to Home
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
      
      <footer className="border-t border-[#222222] py-8 bg-black">
        <div className="container mx-auto flex flex-col md:flex-row items-center justify-center gap-4 px-4 md:px-6">
          <div className="flex items-center gap-2">
            <Brain className="h-5 w-5 text-purple-400" />
            <span className="text-lg font-semibold">Synapse</span>
          </div>
          <p className="text-center text-sm text-white/50 md:text-left">
            &copy; {new Date().getFullYear()} Synapse. All rights reserved.
          </p>
          <div className="flex items-center gap-4 md:ml-auto">
            <a href="https://github.com" target="_blank" rel="noopener noreferrer" className="text-white/50 hover:text-white/80 transition-colors">
              <Github className="h-5 w-5" />
            </a>
            <a href="https://twitter.com" target="_blank" rel="noopener noreferrer" className="text-white/50 hover:text-white/80 transition-colors">
              <Twitter className="h-5 w-5" />
            </a>
            <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer" className="text-white/50 hover:text-white/80 transition-colors">
              <Linkedin className="h-5 w-5" />
            </a>
            <div className="hidden md:block border-l border-[#333333] h-5 mx-2"></div>
            <Link href="#" className="text-sm text-white/50 hover:text-white/80">
              Privacy Policy
            </Link>
            <Link href="#" className="text-sm text-white/50 hover:text-white/80">
              Terms of Service
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}